name: split_icon
description: A command package that dynamically loads the flable-icons font file
version: 0.2.0
homepage: https://github.com/flutter-studio/split_icon.git
author: flutter-studio<2534290808@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies: 
  yaml: ^2.2.0
  path: ^1.6.0
  io: ^0.3.4

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0

executables:
  split_icon:

