name: split_icon
description: A command package that dynamically loads the flutter-icons font file
version: 0.6.0
author: Sascha Heim<developers@think-big-company.com>
homepage: https://github.com/ThinkBIG-Company/split_icons.git

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies: 
  yaml: ^3.1.0
  path: ^1.8.0
  io: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3

executables:
  split_icon:

